import Head from 'next/head';
import PropTypes from 'prop-types';

import {StyledContainer} from './Layout.styled';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Crack the code test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <StyledContainer>{children}</StyledContainer>
    </>
  );
};

Layout.propTypes = {

  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node
  ]).isRequired,
};

export default Layout;
